# Abaqus Python Script for Parametric Masonry Wall
# Generated by Antigravity Masonry Simulator

from abaqus import *
from abaqusConstants import *
import regionToolset
import math

# Project Parameters
wall_height = 3.2
wall_width = 5.0
wall_thickness = 0.2
has_window = True
window_width = 1.0
window_height = 1.2
sill_height = 0.9
wind_pressure = 1.5 * 1000 # Convert kPa to Pa
wind_direction = "Out-of-plane (perpendicular to wall)"

# 1. Model & Part Creation
myModel = mdb.models.changeKey(fromName='Model-1', toName='MasonryWallModel')
myPart = myModel.Part(name='Wall', dimensionality=THREE_D, type=DEFORMABLE_BODY)

# Sketching the Wall
mySketch = myModel.ConstrainedSketch(name='WallProfile', sheetSize=20.0)
mySketch.rectangle(point1=(0.0, 0.0), point2=(wall_width, wall_height))

if has_window:
    # Assuming window is centered horizontally
    w_x1 = (wall_width - window_width) / 2.0
    w_x2 = w_x1 + window_width
    w_y1 = sill_height
    w_y2 = sill_height + window_height
    mySketch.rectangle(point1=(w_x1, w_y1), point2=(w_x2, w_y2))

myPart.BaseSolidExtrude(sketch=mySketch, depth=wall_thickness)

# 2. Material Definition (Concrete Damage Plasticity)
myMaterial = myModel.Material(name='Masonry_CDP')
myMaterial.Density(table=((2000.0, ), ))
myMaterial.Elastic(table=((10e9, 0.2), ))
myMaterial.ConcreteDamagedPlasticity(table=((38.0, 0.1, 1.16, 0.66, 0.0), ))
myMaterial.concreteDamagedPlasticity.ConcreteCompressionHardening(table=((15e6, 0.0), (20e6, 0.001), (15e6, 0.003)))
myMaterial.concreteDamagedPlasticity.ConcreteTensionStiffening(table=((1.5e6, 0.0), (0.0, 0.002)))
myMaterial.concreteDamagedPlasticity.ConcreteTensionDamage(table=((0.0, 0.0), (0.9, 0.002)))

# Section Assignment
myModel.HomogeneousSolidSection(name='WallSection', material='Masonry_CDP', thickness=None)
region = regionToolset.Region(cells=myPart.cells)
myPart.SectionAssignment(region=region, sectionName='WallSection')

# 3. Assembly & Step
myAssembly = myModel.rootAssembly
myInstance = myAssembly.Instance(name='Wall-1', part=myPart, dependent=ON)

myModel.StaticStep(name='ApplyLoads', previous='Initial', nlgeom=ON)

# 4. Boundary Conditions - Fixed Base (Engaste)
faces = myInstance.faces
base_face = faces.findAt(((wall_width/2.0, 0.0, wall_thickness/2.0),))
base_region = regionToolset.Region(faces=base_face)
myModel.EncastreBC(name='FixedBase', createStepName='Initial', region=base_region)

# 5. Loads (Wind Pressure)
# Apply pressure to the external face (Z=thickness for out-of-plane, X=0 for in-plane)
if wind_direction == "Out-of-plane (perpendicular to wall)":
     front_face = faces.findAt(((wall_width/2.0, wall_height/2.0, wall_thickness),))
     load_region = regionToolset.Region(faces=front_face)
     myModel.Pressure(name='WindLoad', createStepName='ApplyLoads', region=load_region, magnitude=wind_pressure)
else:
     # In-plane load applied on the side edge
     side_face = faces.findAt(((0.0, wall_height/2.0, wall_thickness/2.0),))
     load_region = regionToolset.Region(faces=side_face)
     myModel.Pressure(name='WindLoad', createStepName='ApplyLoads', region=load_region, magnitude=wind_pressure)

# 6. Meshing
myPart.seedPart(size=0.1, deviationFactor=0.1, minSizeFactor=0.1)
myPart.generateMesh()

# 7. Job Creation
myJob = mdb.Job(name='MasonryWallJob', model='MasonryWallModel')
print("Abaqus model script completed successfully.")
# myJob.submit(consistencyChecking=OFF) # Uncomment to auto-run
