def generate_chrono_script(params):
    """
    Generates a PyChrono script for simulating the masonry wall.
    """
    wall_height = params['wall_height']
    wall_width = params['wall_width']
    wall_thickness = params['wall_thickness']
    has_window = params['has_window']
    window_width = params.get('window_width', 0)
    window_height = params.get('window_height', 0)
    sill_height = params.get('sill_height', 0)
    window_offset_x = params.get('window_offset_x', 0)
    wind_pressure = params['wind_pressure']
    wind_direction = params['wind_direction']
    apply_frp = params.get('apply_frp', False)
    brick_length = params.get('brick_length', 0.203)
    brick_height = params.get('brick_height', 0.057)
    brick_depth = params.get('brick_depth', 0.095)
    mortar_thickness = params.get('mortar_thickness', 0.010)
    wythes = params.get('wythes', 1)
    
    script = f'''# PyChrono Script for Dynamic Masonry Wall Collapse
# Generated by Antigravity Masonry Simulator

import pychrono as chrono
import pychrono.irrlicht as chronoirr
import math

# 1. System Configuration
system = chrono.ChSystemNSC()
system.Set_G_acc(chrono.ChVector3d(0, -9.81, 0))

# 2. Material properties for bricks and mortar interaction
brick_material = chrono.ChContactMaterialNSC()
brick_material.SetFriction(0.7)
brick_material.SetRestitution(0.1)
# Cohesion simulates the mortar bond strength before failure
brick_material.SetCohesion(50000) # Reduced to allow yielding under 135mph+ winds

# 3. Geometric Parameters
brick_x = {brick_length}
brick_y = {brick_height}
brick_z = {brick_depth}
mortar = {mortar_thickness}
wythes = {wythes}

wall_width = {wall_width}
wall_height = {wall_height}

cols = int(math.ceil(wall_width / (brick_x + mortar))) + 1
rows = int(math.ceil(wall_height / (brick_y + mortar)))

has_window = {has_window}
w_width = {window_width}
w_height = {window_height}
s_height = {sill_height}

# Central window limits
w_x_min = {window_offset_x}
w_x_max = w_x_min + w_width
w_y_min = s_height
w_y_max = s_height + w_height

def is_inside_opening(x, y):
    if not has_window: return False
    # Check if brick center is inside the window box
    return w_x_min <= x <= w_x_max and w_y_min <= y <= w_y_max

bricks = []

# 4. Wall Construction Loop (Running Bond Pattern)
for w in range(wythes):
    pos_z = w * (brick_z + mortar)
    for r in range(rows):
        off_x = 0.0 if r % 2 == 0 else -brick_x / 2.0
        for c in range(cols):
            pos_x = off_x + c * (brick_x + mortar)
            pos_y = r * (brick_y + mortar)
            
            b_len = brick_x
            
            # Boundary clamping (Half bricks on edges)
            if pos_x < -1e-5:
                pos_x = 0.0
                b_len = brick_x / 2.0
            elif pos_x + brick_x > wall_width + 1e-4:
                if pos_x < wall_width - 1e-4:
                    b_len = brick_x / 2.0
                else:
                    continue # Entirely outside
            
            # Brick center for placement and window checking
            bc_x = pos_x + b_len / 2.0
            bc_y = pos_y + brick_y / 2.0
            bc_z = pos_z + brick_z / 2.0
            
            # Omit bricks that fall inside the window
            if not is_inside_opening(bc_x, bc_y):
                brick = chrono.ChBodyEasyBox(b_len, brick_y, brick_z, 1800, True, True, brick_material)
                brick.SetPos(chrono.ChVector3d(bc_x, bc_y, bc_z))
                system.Add(brick)
                bricks.append(brick)
                
                # Apply Lateral Wind Load as constant force (simplified equivalent pressure * area)
                wind_press = {wind_pressure} * 1000 # Pa
                face_area = b_len * brick_y if "{wind_direction}" == "Out-of-plane (perpendicular to wall)" else brick_y * brick_z
                force_mag = wind_press * face_area
                
                # Use ChForce to apply lateral loads
                myforce = chrono.ChForce()
                brick.AddForce(myforce)
                myforce.SetMode(chrono.ChForce.FORCE)
                if "{wind_direction}" == "Out-of-plane (perpendicular to wall)":
                    myforce.SetVrelpoint(chrono.ChVector3d(0, 0, 0))
                    myforce.SetMforce(force_mag)
                    myforce.SetDir(chrono.ChVector3d(0, 0, 1)) # Z direction
                else:
                    myforce.SetVrelpoint(chrono.ChVector3d(0, 0, 0))
                    myforce.SetMforce(force_mag)
                    myforce.SetDir(chrono.ChVector3d(1, 0, 0)) # X direction

# 5. Fixed Ground/Support (Engaste)
floor = chrono.ChBodyEasyBox(wall_width * 2, 0.5, wall_width * 2, 1000, True, True, brick_material)
floor.SetPos(chrono.ChVector3d(wall_width / 2.0, -0.25, 0))
floor.SetFixed(True)
system.Add(floor)

# Simulate Fixed Base by severely restricting the lowest course of bricks
# This creates the "engaste" effect required to correlate with Abaqus.
for b in bricks:
    pos = b.GetPos()
    if pos.y < brick_y: # Bottom row
        b.SetFixed(True)

# 6. Optional FRP Reinforcement Loop
apply_frp = {apply_frp}
if apply_frp:
    print("Applying FRP strips (using constraints/FEA) as stabilization...")
    # FEA mesh logic would be implemented here bridging vertical strips mapping.

# 7. Visualization Loop
vis = chronoirr.ChVisualSystemIrrlicht()
vis.AttachSystem(system)
vis.SetWindowSize(1280, 720)
vis.SetWindowTitle('Masonry Wall Collapse Simulation (Antigravity)')
vis.Initialize()
vis.AddLogo(chronoirr.GetChronoDataFile('logo_pychrono_alpha.png'))
vis.AddSkyBox()
vis.AddCamera(chrono.ChVector3d(wall_width / 2.0, wall_height / 2.0, -wall_height * 1.5))
vis.AddTypicalLights()

while vis.Run():
    vis.BeginScene()
    vis.Render()
    vis.EndScene()
    system.DoStepDynamics(0.005)
'''
    return script
