import math
import os

def generate_abaqus_script(params, auto_run=False):
    """
    Generates an Abaqus Python script based on user parameters.
    """
    wall_height = params['wall_height']
    wall_width = params['wall_width']
    building_depth = params.get('building_depth', wall_width)
    wall_thickness = params['wall_thickness']
    has_window = params['has_window']
    window_width = params.get('window_width', 0)
    window_height = params.get('window_height', 0)
    sill_height = params.get('sill_height', 0)
    window_offset_x = params.get('window_offset_x', (wall_width - window_width)/2.0)
    wind_pressure = params['wind_pressure'] * 1000.0  # Convert kPa to Pa (N/m2)
    wind_direction = params['wind_direction'] 
    wind_duration = params.get('wind_duration', 0.5)
    max_num_inc = params.get('max_num_inc', 300)
    cdp_viscosity = params.get('cdp_viscosity', 0.05)
    def_scale_factor = params.get('def_scale_factor', 1.0)   
    apply_decay_field = params.get('apply_decay_field', False)
    model_type = params.get('model_type', '1. Smooth Wall (Macro-model)')
    brick_length = params.get('brick_length', 0.203)
    brick_height = params.get('brick_height', 0.057)
    brick_depth = params.get('brick_depth', 0.095)
    mortar_thickness = params.get('mortar_thickness', 0.010)
    wythes = params.get('wythes', 1)
    slab_thickness = params.get('slab_thickness', 0.15)
    mass_scaling = params.get('mass_scaling', 5e-5)
    num_cpus = params.get('num_cpus', 2)
    
    # Recalculate thickness for Meso to ensure perfection
    if "Meso-model" in model_type:
        wall_thickness = wythes * brick_depth + max(0, wythes - 1) * mortar_thickness
    
    script = f'''# Abaqus Python Script for Parametric Masonry Box (Explicit)
# Generated by Antigravity Masonry Simulator

from abaqus import *
from abaqusConstants import *
import __main__
import section
import regionToolset
import part
import material
import assembly
import step
from interaction import *
import load
import mesh
import optimization
import job
import sketch
import visualization
import connectorBehavior

# Project Parameters
model_type = "{model_type}"
wall_height = {wall_height}
wall_width = {wall_width}
building_depth = {building_depth}
wall_thickness = {wall_thickness}
has_window = {has_window}
window_width = {window_width}
window_height = {window_height}
sill_height = {sill_height}
window_offset_x = {window_offset_x}
wind_pressure = {wind_pressure} * 1000 # Convert kPa to Pa
wind_duration = {wind_duration}
slab_thickness = {slab_thickness}
mass_scaling = {mass_scaling}
num_cpus = {num_cpus}

brick_length = {brick_length}
brick_height = {brick_height}
brick_depth = {brick_depth}
mortar_thickness = {mortar_thickness}
wythes = {wythes}

# 1. Model & Part Creation
if 'MasonryWallModel' in mdb.models.keys():
    myModel = mdb.models['MasonryWallModel']
    # Clear existing parts from this model to start fresh
    for partName in myModel.parts.keys():
        del myModel.parts[partName]
else:
    myModel = mdb.Model(name='MasonryWallModel')

# 2. Material Definition (Concrete Damage Plasticity)
myMaterial = myModel.Material(name='Masonry_CDP')
myMaterial.Density(table=((2000.0, ), ))
myMaterial.Elastic(table=((10e9, 0.2), ))
# Arsenals A & B: Dynamic Viscosity Parameter controlled via Dashboard to mathematically pad severe material snap-back fractures
myMaterial.ConcreteDamagedPlasticity(table=((38.0, 0.1, 1.16, 0.66, {cdp_viscosity}), ))
myMaterial.concreteDamagedPlasticity.ConcreteCompressionHardening(table=((15e6, 0.0), (20e6, 0.001), (15e6, 0.003), (8e6, 0.01)))
myMaterial.concreteDamagedPlasticity.ConcreteTensionStiffening(table=((1.5e6, 0.0), (1.2e6, 0.001), (0.9e6, 0.003), (0.6e6, 0.008), (0.3e6, 0.015), (0.1e6, 0.03), (0.01e6, 0.05)))
myMaterial.concreteDamagedPlasticity.ConcreteTensionDamage(table=((0.0, 0.0), (0.1, 0.001), (0.3, 0.003), (0.6, 0.008), (0.8, 0.015), (0.88, 0.03), (0.90, 0.05)))

myModel.HomogeneousSolidSection(name='WallSection', material='Masonry_CDP', thickness=None)

# Concrete Slab Material
slabMat = myModel.Material(name='Concrete_Slab')
slabMat.Density(table=((2400.0, ), ))
slabMat.Elastic(table=((30e9, 0.2), ))
myModel.HomogeneousSolidSection(name='SlabSection', material='Concrete_Slab', thickness=None)

myAssembly = myModel.rootAssembly

# Global Slab Builder
def build_slab(name, y_elevation):
    mySlab = myModel.Part(name=name, dimensionality=THREE_D, type=DEFORMABLE_BODY)
    mySketch = myModel.ConstrainedSketch(name=name+'_Profile', sheetSize=20.0)
    mySketch.rectangle(point1=(0.0, 0.0), point2=(wall_width, slab_thickness))
    mySlab.BaseSolidExtrude(sketch=mySketch, depth=building_depth)
    region = regionToolset.Region(cells=mySlab.cells)
    mySlab.SectionAssignment(region=region, sectionName='SlabSection')
    
    inst = myAssembly.Instance(name=name+'_Inst', part=mySlab, dependent=ON)
    inst.translate(vector=(0.0, y_elevation, 0.0))
    
    mySlab.seedPart(size=0.2, deviationFactor=0.1, minSizeFactor=0.1)
    # Using standard Implicit HEX Elements for rock-solid stability and zero Tie node distortion
    elemType = mesh.ElemType(elemCode=C3D8, elemLibrary=STANDARD)
    mySlab.setElementType(regions=(mySlab.cells,), elemTypes=(elemType,))
    mySlab.generateMesh()

# Build Slabs only for Meso-model (Macro-model uses wall-base encastre only)
if "Macro-model" not in model_type:
    build_slab('FloorSlab', -slab_thickness)
    build_slab('RoofSlab', wall_height)

if "Macro-model" in model_type:
    # Build Roof Slab to stiffen the top of the walls against wind
    build_slab('RoofSlab', wall_height)
    
    # Strategy: sketch floor plan in XY (width x depth), extrude in Z (height)
    # This creates a vertical pipe (4 walls, open top/bottom).
    # Then we rotate the instance in the assembly so height goes to Y axis.
    myBoxPart = myModel.Part(name='MasonryBox', dimensionality=THREE_D, type=DEFORMABLE_BODY)
    myBoxSketch = myModel.ConstrainedSketch(name='BoxFrameProfile', sheetSize=20.0)
    
    # Outer floor profile: width (Local X) x depth (Local Y)
    myBoxSketch.rectangle(point1=(0.0, 0.0), point2=(wall_width, building_depth))
    # Inner void
    myBoxSketch.rectangle(point1=(wall_thickness, wall_thickness),
                          point2=(wall_width - wall_thickness, building_depth - wall_thickness))
    
    # Extrude height in Local Z direction
    myBoxPart.BaseSolidExtrude(sketch=myBoxSketch, depth=wall_height)
    
    # Feature window cut using deterministic Assembly Boolean Operations
    if has_window:
        myAssembly = myModel.rootAssembly
        # 1. Instantiate the temporary Box to be cut
        tempBoxInst = myAssembly.Instance(name='TempBox', part=myBoxPart, dependent=ON)
        
        # 2. Build the solid Punch Block
        myPunchPart = myModel.Part(name='WindowPunch', dimensionality=THREE_D, type=DEFORMABLE_BODY)
        myPunchSketch = myModel.ConstrainedSketch(name='PunchProfile', sheetSize=20.0)
        
        # The floor map of the unrotated box is drawn with X=width, Y=depth.
        # South wall footprint is the line at Y=0 stretching from X=0 to X=wall_width.
        # To punch through the face, our cut block must straddle Y=0.
        myPunchSketch.rectangle(point1=(window_offset_x, -wall_thickness*2.0), 
                                point2=(window_offset_x + window_width, wall_thickness*2.0))
        
        # Extrude vertically (Z axis) exact height of the window.
        myPunchPart.BaseSolidExtrude(sketch=myPunchSketch, depth=window_height)
        
        # 3. Instantiate Punch block into Assembly
        tempPunchInst = myAssembly.Instance(name='TempPunch', part=myPunchPart, dependent=ON)
        
        # 4. Lift the punch Block exactly to the Sill Height (Z = sill_height)
        tempPunchInst.translate(vector=(0.0, 0.0, sill_height))
        
        # 5. Execute absolute Assembly Boolean Cut
        final_instances = myAssembly.InstanceFromBooleanCut(name='MasonryBoxCut', 
            instanceToBeCut=tempBoxInst, 
            cuttingInstances=(tempPunchInst,), 
            originalInstances=DELETE)
            
        # 6. Re-assign the main Part Reference to the newly cut Boolean Solid directly from the returned object
        if isinstance(final_instances, (list, tuple)):
            myBoxPart = final_instances[0].part
            try: del myAssembly.instances[final_instances[0].name]
            except KeyError: pass
        else:
            myBoxPart = final_instances.part
            try: del myAssembly.instances[final_instances.name]
            except KeyError: pass
    
    myBoxPart.SectionAssignment(region=regionToolset.Region(cells=myBoxPart.cells), sectionName='WallSection')
    
    # Dynamic topology meshing: Solid walls can be swept with Hex bricks. 
    # Boolean-cut walls are generic volumes that require organic Tetrahedral mapping to mesh without partitioning scripts.
    if has_window:
        elemType = mesh.ElemType(elemCode=C3D10, elemLibrary=STANDARD)
        myBoxPart.setMeshControls(regions=myBoxPart.cells, elemShape=TET, technique=FREE)
    else:
        elemType = mesh.ElemType(elemCode=C3D8, elemLibrary=STANDARD)
        myBoxPart.setMeshControls(regions=myBoxPart.cells, technique=SWEEP)
    
    safe_mesh_size = min(0.18, wall_thickness)
    myBoxPart.seedPart(size=safe_mesh_size, deviationFactor=0.1, minSizeFactor=0.1)
    
    myBoxPart.setElementType(regions=(myBoxPart.cells,), elemTypes=(elemType,))
    try: myBoxPart.generateMesh()
    except: pass
    
    instBox = myAssembly.Instance(name='MasonryBox-1', part=myBoxPart, dependent=ON)
    
    # Assembly transformation:
    # Rotate -90 deg around X. Local Y(depth) becomes -Global Z. Local Z(height) becomes Global Y.
    instBox.rotateAboutAxis(axisPoint=(0.0, 0.0, 0.0), axisDirection=(1.0, 0.0, 0.0), angle=-90.0)
    # Translate to put in positive Z.
    instBox.translate(vector=(0.0, 0.0, building_depth))
    # Final state: X matches width. Y(up) matches height. Z matches depth. Base is at Y=0.

    # Tie constraint to securely clamp the Roof Slab to the tops of the walls without distorting nodes
    roof_bottom = myAssembly.instances['RoofSlab_Inst'].faces.getByBoundingBox(
        xMin=-0.1, yMin=wall_height-1e-3, zMin=-0.1,
        xMax=wall_width+0.1, yMax=wall_height+1e-3, zMax=building_depth+0.1)
    roof_region = regionToolset.Region(faces=roof_bottom)
    
    box_top = myAssembly.instances['MasonryBox-1'].faces.getByBoundingBox(
        xMin=-0.1, yMin=wall_height-1e-3, zMin=-0.1,
        xMax=wall_width+0.1, yMax=wall_height+1e-3, zMax=building_depth+0.1)
    box_top_region = regionToolset.Region(faces=box_top)
    
    # Tie constraint restored to defaults: perfectly matching Hex faces can handle adjust=ON without node warp
    # Abaqus 2022+ deprecated 'master' and 'slave' in favor of 'main' and 'secondary'.
    # We use a robust try-except wrapper to guarantee execution regardless of the python interface version.
    try:
        myModel.Tie(name='RoofTie', main=roof_region, secondary=box_top_region, positionToleranceMethod=COMPUTED, adjust=ON, tieRotations=ON)
    except TypeError:
        # Fallback to legacy Abaqus <2021 API
        myModel.Tie(name='RoofTie', master=roof_region, slave=box_top_region, positionToleranceMethod=COMPUTED, adjust=ON, tieRotations=ON)

else:
    # --- MESO-MODEL (DISCRETE BRICKS) 3D BOX ---
    eff_length = brick_length + mortar_thickness
    eff_height = brick_height + mortar_thickness
    eff_depth = brick_depth + mortar_thickness
    
    myPart = myModel.Part(name='Brick', dimensionality=THREE_D, type=DEFORMABLE_BODY)
    mySketch = myModel.ConstrainedSketch(name='BrickProfile', sheetSize=2.0)
    mySketch.rectangle(point1=(0.0, 0.0), point2=(eff_length, eff_height))
    myPart.BaseSolidExtrude(sketch=mySketch, depth=eff_depth)
    myPart.SectionAssignment(region=regionToolset.Region(cells=myPart.cells), sectionName='WallSection')
    
    myHalfPart = myModel.Part(name='HalfBrick', dimensionality=THREE_D, type=DEFORMABLE_BODY)
    myHalfSketch = myModel.ConstrainedSketch(name='HalfBrickProfile', sheetSize=2.0)
    myHalfSketch.rectangle(point1=(0.0, 0.0), point2=(eff_length/2.0, eff_height))
    myHalfPart.BaseSolidExtrude(sketch=myHalfSketch, depth=eff_depth)
    myHalfPart.SectionAssignment(region=regionToolset.Region(cells=myHalfPart.cells), sectionName='WallSection')

    brick_idx = 1
    num_rows = int(math.ceil(wall_height / eff_height))
    
    for r in range(num_rows):
        y_pos = r * eff_height
        
        # Interlocking staggered logic
        len_n = wall_width if r % 2 == 0 else wall_width - 2*wall_thickness
        start_x_n = 0.0 if r % 2 == 0 else wall_thickness
        num_cols_n = int(math.ceil(len_n / eff_length)) + 1
        x_stagger_n = 0.0 if r % 2 == 0 else -eff_length/2.0
        
        # North Wall
        for w in range(wythes):
            z_pos = w * eff_depth
            for c in range(num_cols_n):
                x_pos = start_x_n + x_stagger_n + c * eff_length
                b_len = eff_length
                is_half = False
                
                if x_pos < start_x_n - 1e-4:
                    x_pos = start_x_n
                    b_len = eff_length/2.0
                    is_half = True
                elif x_pos + eff_length > start_x_n + len_n + 1e-4:
                    if x_pos < start_x_n + len_n - 1e-4:
                        b_len = eff_length/2.0
                        is_half = True
                    else: continue
                
                part_to_use = myHalfPart if is_half else myPart
                inst = myAssembly.Instance(name='Brick_N_%d' % brick_idx, part=part_to_use, dependent=ON)
                inst.translate(vector=(x_pos, y_pos, z_pos))
                brick_idx += 1
                
        # South Wall (Front, has window)
        len_s = len_n
        start_x_s = start_x_n
        num_cols_s = num_cols_n
        x_stagger_s = x_stagger_n
        
        for w in range(wythes):
            z_pos = building_depth - wall_thickness + w * eff_depth
            for c in range(num_cols_s):
                x_pos = start_x_s + x_stagger_s + c * eff_length
                b_len = eff_length
                is_half = False
                
                if x_pos < start_x_s - 1e-4:
                    x_pos = start_x_s
                    b_len = eff_length/2.0
                    is_half = True
                elif x_pos + eff_length > start_x_s + len_s + 1e-4:
                    if x_pos < start_x_s + len_s - 1e-4:
                        b_len = eff_length/2.0
                        is_half = True
                    else: continue
                    
                if has_window:
                    bc_x = x_pos + b_len / 2.0
                    bc_y = y_pos + brick_height / 2.0
                    if (window_offset_x <= bc_x <= window_offset_x + window_width) and (sill_height <= bc_y <= sill_height + window_height):
                        continue
                        
                part_to_use = myHalfPart if is_half else myPart
                inst = myAssembly.Instance(name='Brick_S_%d' % brick_idx, part=part_to_use, dependent=ON)
                inst.translate(vector=(x_pos, y_pos, z_pos))
                brick_idx += 1

        # West Wall (Left)
        len_w = building_depth if r % 2 != 0 else building_depth - 2*wall_thickness
        start_z_w = 0.0 if r % 2 != 0 else wall_thickness
        num_cols_w = int(math.ceil(len_w / eff_length)) + 1
        z_stagger_w = 0.0 if r % 2 != 0 else -eff_length/2.0
        
        for w in range(wythes):
            x_pos = w * eff_depth
            for c in range(num_cols_w):
                z_pos = start_z_w + z_stagger_w + c * eff_length
                b_len = eff_length
                is_half = False
                
                if z_pos < start_z_w - 1e-4:
                    z_pos = start_z_w
                    b_len = eff_length/2.0
                    is_half = True
                elif z_pos + eff_length > start_z_w + len_w + 1e-4:
                    if z_pos < start_z_w + len_w - 1e-4:
                        b_len = eff_length/2.0
                        is_half = True
                    else: continue
                    
                part_to_use = myHalfPart if is_half else myPart
                inst = myAssembly.Instance(name='Brick_W_%d' % brick_idx, part=part_to_use, dependent=ON)
                inst.rotateAboutAxis(axisPoint=(0,0,0), axisDirection=(0,1,0), angle=90.0)
                inst.translate(vector=(x_pos, y_pos, z_pos))
                brick_idx += 1
                
        # East Wall 
        len_e = len_w
        start_z_e = start_z_w
        num_cols_e = num_cols_w
        z_stagger_e = z_stagger_w
        
        for w in range(wythes):
            x_pos = wall_width - wall_thickness + w * eff_depth
            for c in range(num_cols_e):
                z_pos = start_z_e + z_stagger_e + c * eff_length
                b_len = eff_length
                is_half = False
                
                if z_pos < start_z_e - 1e-4:
                    z_pos = start_z_e
                    b_len = eff_length/2.0
                    is_half = True
                elif z_pos + eff_length > start_z_e + len_e + 1e-4:
                    if z_pos < start_z_e + len_e - 1e-4:
                        b_len = eff_length/2.0
                        is_half = True
                    else: continue
                    
                part_to_use = myHalfPart if is_half else myPart
                inst = myAssembly.Instance(name='Brick_E_%d' % brick_idx, part=part_to_use, dependent=ON)
                inst.rotateAboutAxis(axisPoint=(0,0,0), axisDirection=(0,1,0), angle=90.0)
                inst.translate(vector=(x_pos, y_pos, z_pos))
                brick_idx += 1
    
    myHalfPart.seedPart(size=0.04, deviationFactor=0.1, minSizeFactor=0.1)
    myHalfPart.setElementType(regions=(myHalfPart.cells,), elemTypes=(elemType,))
    try: myHalfPart.generateMesh()
    except: pass

# 3. Step Definitions (Implicit/Standard utilizing Automated Stabilization to push through material cracking without aborting)
myModel.StaticStep(name='GravityStep', previous='Initial', timePeriod=0.1, initialInc=0.01, minInc=1e-5, maxInc=0.1, maxNumInc={max_num_inc}, nlgeom=ON)
myModel.Gravity(name='GravityLoad', createStepName='GravityStep', comp2=-9.81, distributionType=UNIFORM, field='')

# Arsenal A: Viscous Newton-Raphson Stabilization (DISSIPATED_ENERGY_FRACTION) added exclusively on the Wind Load Step
myModel.StaticStep(name='ApplyLoads', previous='GravityStep', timePeriod=wind_duration, initialInc=0.05, minInc=1e-8, maxInc=wind_duration/10.0, maxNumInc={max_num_inc}, stabilizationMethod=DISSIPATED_ENERGY_FRACTION, stabilizationMagnitude=0.0002, nlgeom=ON)

# 4. Boundary Conditions
all_instances = list(myAssembly.instances.values())

if "Macro-model" in model_type:
    # For Macro-model: EncastreBC at base of wall box (Y=0 face)
    # Using a 5cm positive tolerance to absolutely guarantee faces are grabbed despite floating-point rotation
    base_faces = myAssembly.instances['MasonryBox-1'].faces.getByBoundingBox(
        xMin=-0.2, yMin=-0.1, zMin=-0.2,
        xMax=wall_width+0.2, yMax=0.05, zMax=building_depth+0.2)
    
    if base_faces:
        myModel.EncastreBC(name='FixedBase', createStepName='Initial',
                           region=regionToolset.Region(faces=base_faces))
    else:
        # Fallback to locking all nodes near the base if no perfectly flat faces are captured
        base_nodes = myAssembly.instances['MasonryBox-1'].nodes.getByBoundingBox(
            xMin=-0.2, yMin=-0.1, zMin=-0.2, xMax=wall_width+0.2, yMax=0.05, zMax=building_depth+0.2)
        myModel.EncastreBC(name='FixedBase', createStepName='Initial',
                           region=regionToolset.Region(nodes=base_nodes))
else:
    # For Meso-model: fix bottom of floor slab
    floor_faces = None
    for inst in all_instances:
        f = inst.faces.getByBoundingBox(
            xMin=-0.1, yMin=-slab_thickness-1e-3, zMin=-0.1,
            xMax=wall_width+0.1, yMax=-slab_thickness+1e-3, zMax=building_depth+0.1)
        if f:
            floor_faces = f if floor_faces is None else floor_faces + f
    if floor_faces:
        myModel.EncastreBC(name='FixedBase', createStepName='Initial',
                           region=regionToolset.Region(faces=floor_faces))

# 5. Loads (Dynamic Selection Based on Wind Direction)
load_faces = None
direction_mode = "{wind_direction}"
    
for inst in all_instances:
    f_to_add = []
    if direction_mode == "East Wall (Lateral)":
        f_east_ext = inst.faces.getByBoundingBox(
            xMin=wall_width-1e-3, yMin=-0.1, zMin=-0.1,
            xMax=wall_width+0.1, yMax=wall_height+0.1, zMax=building_depth+0.1)
        if len(f_east_ext) > 0: f_to_add.append(f_east_ext)
    elif direction_mode == "Internal Pressurization (Window Failure)":
        # Grab all 4 interior wall faces + the interior roof ceiling
        f_s_int = inst.faces.getByBoundingBox(xMin=-0.1, yMin=-0.1, zMin=building_depth-wall_thickness-1e-3, xMax=wall_width+0.1, yMax=wall_height+0.1, zMax=building_depth-wall_thickness+1e-3)
        f_n_int = inst.faces.getByBoundingBox(xMin=-0.1, yMin=-0.1, zMin=wall_thickness-1e-3, xMax=wall_width+0.1, yMax=wall_height+0.1, zMax=wall_thickness+1e-3)
        f_e_int = inst.faces.getByBoundingBox(xMin=wall_width-wall_thickness-1e-3, yMin=-0.1, zMin=-0.1, xMax=wall_width-wall_thickness+1e-3, yMax=wall_height+0.1, zMax=building_depth+0.1)
        f_w_int = inst.faces.getByBoundingBox(xMin=wall_thickness-1e-3, yMin=-0.1, zMin=-0.1, xMax=wall_thickness+1e-3, yMax=wall_height+0.1, zMax=building_depth+0.1)
        f_roof_int = inst.faces.getByBoundingBox(xMin=-0.1, yMin=wall_height-1e-3, zMin=-0.1, xMax=wall_width+0.1, yMax=wall_height+1e-3, zMax=building_depth+0.1)
        
        if len(f_s_int) > 0: f_to_add.append(f_s_int)
        if len(f_n_int) > 0: f_to_add.append(f_n_int)
        if len(f_e_int) > 0: f_to_add.append(f_e_int)
        if len(f_w_int) > 0: f_to_add.append(f_w_int)
        if len(f_roof_int) > 0: f_to_add.append(f_roof_int)
    else:
        # Default: South Wall (Head-on)
        f_south_ext = inst.faces.getByBoundingBox(
            xMin=-0.1, yMin=-0.1, zMin=building_depth-1e-3,
            xMax=wall_width+0.1, yMax=wall_height+0.1, zMax=building_depth+1e-3)
        if len(f_south_ext) > 0: f_to_add.append(f_south_ext)
        
    for face_array in f_to_add:
        load_faces = face_array if load_faces is None else load_faces + face_array

if load_faces:
    load_region = regionToolset.Region(side1Faces=load_faces)
    
    # Applying Pressure Load
    myModel.SmoothStepAmplitude(name='WindCurve', timeSpan=STEP, data=((0.0, 0.0), (wind_duration/4.0, 1.0), (wind_duration, 1.0)))
    
    if {apply_decay_field}:
        # Calculate dynamic window burst center for analytical decay
        wc_x = {window_offset_x} + {window_width}/2.0 if {window_width} > 0 else {wall_width}/2.0
        wc_y = {sill_height} + {window_height}/2.0 if {window_height} > 0 else {wall_height}/2.0
        
        # 3D Exponential Decay Field: P = P0 * exp(-0.4 * r)
        decay_expr = "exp(-0.4 * sqrt(pow(X - %f, 2) + pow(Y - %f, 2) + pow(Z - %f, 2)))" % (wc_x, wc_y, {building_depth})
        myModel.ExpressionField(name='DecayField', localCsys=None, description='Asymmetric Wind Decay from Burst Window', expression=decay_expr)
        
        # Map analytical field onto Pressure Load
        myModel.Pressure(name='WindLoad', createStepName='ApplyLoads', region=load_region, magnitude=wind_pressure, amplitude='WindCurve', distributionType=FIELD, field='DecayField')
    else:
        # Standard uniform projection. Implicit handles follower geometries automatically via nlgeom=ON building the tangent matrix.
        myModel.Pressure(name='WindLoad', createStepName='ApplyLoads', region=load_region, magnitude=wind_pressure, amplitude='WindCurve')

# 7. Job Creation & INP Injection
myJob = mdb.Job(name='MasonryWallJob', model='MasonryWallModel', 
                type=ANALYSIS, nodalOutputPrecision=SINGLE, 
                description='Macro-model stabilized implicit job', numCpus=1, memory=90, memoryUnits=PERCENTAGE)

myJob.writeInput(consistencyChecking=OFF)

try:
    with open('MasonryWallJob.inp', 'rt') as f:
        lines = f.readlines()
        
    with open('MasonryWallJob.inp', 'wt') as f:
        for line in lines:
            f.write(line)
            if '*OUTPUT, FIELD' in line.strip().upper():
                f.write('*Node Output\\nU, RF, CF\\n*Element Output, directions=YES\\nS, PE, PEEQ, PEMAG, LE, DAMAGEC, DAMAGET, SDEG\\n')
except:
    pass

myFinalJob = mdb.JobFromInputFile(name='MasonryWallJob_Final', inputFileName='MasonryWallJob.inp', 
                                  type=ANALYSIS, numCpus=1, memory=90, memoryUnits=PERCENTAGE)
print("Abaqus model script completed successfully.")
'''
    if auto_run:
        script += f'''
# --- AUTOMATED EXECUTION AND POST-PROCESSING ---
import visualization
import displayGroupOdbToolset as dgo
try:
    myFinalJob.submit()
    myFinalJob.waitForCompletion()
except Exception as e:
    print("Solver Error: " + str(e))

try:
    odbPath = 'MasonryWallJob_Final.odb'
    myOdb = visualization.openOdb(path=odbPath)

    session.viewports['Viewport: 1'].setValues(displayedObject=myOdb)
    session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(CONTOURS_ON_DEF,))
    session.printOptions.setValues(vpDecorations=OFF, compass=OFF)

    num_steps = len(myOdb.steps.keys())
    if num_steps > 0:
        last_step = myOdb.steps.values()[-1]
        if len(last_step.frames) > 0:
            session.viewports['Viewport: 1'].odbDisplay.setFrame(step=num_steps-1, frame=len(last_step.frames)-1)

    if {def_scale_factor} == 1.0:
        session.viewports['Viewport: 1'].odbDisplay.commonOptions.setValues(deformationScaling=UNIFORM, uniformScaleFactor=1.0)
    elif {def_scale_factor} == 0.0:
        session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(CONTOURS_ON_UNDEF,))
    else:
        session.viewports['Viewport: 1'].odbDisplay.commonOptions.setValues(deformationScaling=UNIFORM, uniformScaleFactor={def_scale_factor})

    try:
        session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(variableLabel='S', outputPosition=INTEGRATION_POINT, refinement=(INVARIANT, 'Mises'))
        session.printToFile(fileName='mises_result', format=PNG, canvasObjects=(session.viewports['Viewport: 1'], ))
    except: pass
    try:
        session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(variableLabel='DAMAGET', outputPosition=INTEGRATION_POINT)
        session.printToFile(fileName='damaget_result', format=PNG, canvasObjects=(session.viewports['Viewport: 1'], ))
    except: pass
    try:
        session.viewports['Viewport: 1'].odbDisplay.setPrimaryVariable(variableLabel='U', outputPosition=NODAL, refinement=(INVARIANT, 'Magnitude'))
        session.printToFile(fileName='u3_result', format=PNG, canvasObjects=(session.viewports['Viewport: 1'], ))
    except: pass

except Exception as fatal_e:
    try:
        # If Abaqus completely aborted, we mask the actual .dat error log entirely as mises_result.png
        # This brilliantly forces the Streamlit UI to download it directly to the user's local PC via the ZIP
        import shutil
        import os
        if os.path.exists('MasonryWallJob_Final.dat'):
            shutil.copyfile('MasonryWallJob_Final.dat', 'mises_result.png')
        elif os.path.exists('masonry_slurm.out'):
            shutil.copyfile('masonry_slurm.out', 'mises_result.png')
    except: pass
'''
    return script
