def generate_chrono_script(params):
    """
    Generates a PyChrono script for simulating the masonry 3D box.
    """
    wall_height = params['wall_height']
    wall_width = params['wall_width']
    wall_thickness = params['wall_thickness']
    building_depth = params.get('building_depth', wall_width)
    has_window = params['has_window']
    window_width = params.get('window_width', 0)
    window_height = params.get('window_height', 0)
    sill_height = params.get('sill_height', 0)
    window_offset_x = params.get('window_offset_x', 0)
    wind_pressure = params['wind_pressure']
    wind_direction = params['wind_direction']
    wind_duration = params.get('wind_duration', 0.5)
    apply_frp = params.get('apply_frp', False)
    brick_length = params.get('brick_length', 0.203)
    brick_height = params.get('brick_height', 0.057)
    brick_depth = params.get('brick_depth', 0.095)
    mortar_thickness = params.get('mortar_thickness', 0.010)
    wythes = params.get('wythes', 1)
    
    script = f'''# PyChrono Script for Dynamic Masonry Box Collapse
# Generated by Antigravity Masonry Simulator

import pychrono as chrono
import pychrono.irrlicht as chronoirr
import math

# 1. System Configuration
system = chrono.ChSystemNSC()
system.Set_G_acc(chrono.ChVector3d(0, -9.81, 0))

# 2. Material properties for bricks and mortar interaction
brick_material = chrono.ChContactMaterialNSC()
brick_material.SetFriction(0.7)
brick_material.SetRestitution(0.1)
# Cohesion simulates the mortar bond strength before failure
brick_material.SetCohesion(50000)

# 3. Geometric Parameters
brick_x = {brick_length}
brick_y = {brick_height}
brick_z = {brick_depth}
mortar = {mortar_thickness}
wythes = {wythes}

wall_width = {wall_width}
wall_height = {wall_height}
building_depth = {building_depth}
wall_thickness = {wall_thickness}

eff_length = brick_x + mortar
eff_height = brick_y + mortar
eff_depth = brick_z + mortar

rows = int(math.ceil(wall_height / eff_height))

has_window = {has_window}
w_width = {window_width}
w_height = {window_height}
s_height = {sill_height}
w_x_min = {window_offset_x}
w_x_max = w_x_min + w_width
w_y_min = s_height
w_y_max = s_height + w_height

def is_inside_opening(x, y):
    if not has_window: return False
    return w_x_min <= x <= w_x_max and w_y_min <= y <= w_y_max

bricks = []

# 4. 3D Box Construction Loop (Interlocking Running Bond)
for r in range(rows):
    pos_y = r * eff_height + brick_y/2.0
    
    # North Wall (Z=0)
    len_n = wall_width if r % 2 == 0 else wall_width - 2*wall_thickness
    start_x_n = 0.0 if r % 2 == 0 else wall_thickness
    cols_n = int(math.ceil(len_n / eff_length)) + 1
    x_stagger_n = 0.0 if r % 2 == 0 else -eff_length/2.0
    
    for w in range(wythes):
        pos_z = w * eff_depth + brick_z/2.0
        for c in range(cols_n):
            pos_x = start_x_n + x_stagger_n + c * eff_length
            b_len = eff_length
            
            if pos_x < start_x_n - 1e-4:
                pos_x = start_x_n
                b_len = eff_length/2.0
            elif pos_x + eff_length > start_x_n + len_n + 1e-4:
                if pos_x < start_x_n + len_n - 1e-4:
                    b_len = eff_length/2.0
                else: continue
                
            bc_x = pos_x + b_len/2.0
            brick = chrono.ChBodyEasyBox(b_len, brick_y, brick_z, 1800, True, True, brick_material)
            brick.SetPos(chrono.ChVector3d(bc_x, pos_y, pos_z))
            system.Add(brick)
            bricks.append(brick)
            
    # South Wall (Front, has window)
    for w in range(wythes):
        pos_z = building_depth - wall_thickness + w * eff_depth + brick_z/2.0
        for c in range(cols_n):
            pos_x = start_x_n + x_stagger_n + c * eff_length
            b_len = eff_length
            
            if pos_x < start_x_n - 1e-4:
                pos_x = start_x_n
                b_len = eff_length/2.0
            elif pos_x + eff_length > start_x_n + len_n + 1e-4:
                if pos_x < start_x_n + len_n - 1e-4:
                    b_len = eff_length/2.0
                else: continue
                
            bc_x = pos_x + b_len/2.0
            
            if not is_inside_opening(bc_x, pos_y):
                brick = chrono.ChBodyEasyBox(b_len, brick_y, brick_z, 1800, True, True, brick_material)
                brick.SetPos(chrono.ChVector3d(bc_x, pos_y, pos_z))
                
                # Apply Lateral Wind Load (using a constant load body force)
                wind_press = {wind_pressure} * 1000 # Pa
                face_area = b_len * brick_y
                force_mag = wind_press * face_area
                myforce = chrono.ChForce()
                brick.AddForce(myforce)
                myforce.SetMode(chrono.ChForce.FORCE)
                myforce.SetVrelpoint(chrono.ChVector3d(0, 0, 0))
                myforce.SetMforce(force_mag)
                myforce.SetDir(chrono.ChVector3d(0, 0, -1)) # Pushing INTO the building from South
                
                system.Add(brick)
                bricks.append(brick)
                
    # West Wall (Left) / East Wall (Right)
    len_side = building_depth if r % 2 != 0 else building_depth - 2*wall_thickness
    start_z_side = 0.0 if r % 2 != 0 else wall_thickness
    cols_side = int(math.ceil(len_side / eff_length)) + 1
    z_stagger_side = 0.0 if r % 2 != 0 else -eff_length/2.0
    
    for wall_side, x_base in [("West", 0.0), ("East", wall_width - wall_thickness)]:
        for w in range(wythes):
            pos_x = x_base + w * eff_depth + brick_z/2.0
            for c in range(cols_side):
                pos_z_base = start_z_side + z_stagger_side + c * eff_length
                b_len = eff_length
                
                if pos_z_base < start_z_side - 1e-4:
                    pos_z_base = start_z_side
                    b_len = eff_length/2.0
                elif pos_z_base + eff_length > start_z_side + len_side + 1e-4:
                    if pos_z_base < start_z_side + len_side - 1e-4:
                        b_len = eff_length/2.0
                    else: continue
                    
                bc_z = pos_z_base + b_len/2.0
                brick = chrono.ChBodyEasyBox(b_len, brick_y, brick_z, 1800, True, True, brick_material)
                
                # Rotate 90 degrees around Y axis
                quat = chrono.ChQuaterniond()
                quat.SetFromAngleAxis(chrono.CH_C_PI/2.0, chrono.ChVector3d(0,1,0))
                brick.SetRot(quat)
                
                brick.SetPos(chrono.ChVector3d(pos_x, pos_y, bc_z))
                system.Add(brick)
                bricks.append(brick)

# 5. Fixed Ground/Support (Engaste)
floor = chrono.ChBodyEasyBox(wall_width * 3, 0.5, building_depth * 3, 1000, True, True, brick_material)
floor.SetPos(chrono.ChVector3d(wall_width / 2.0, -0.25, building_depth / 2.0))
floor.SetFixed(True)
system.Add(floor)

for b in bricks:
    pos = b.GetPos()
    if pos.y < brick_y: 
        b.SetFixed(True)

# 7. Visualization Loop
vis = chronoirr.ChVisualSystemIrrlicht()
vis.AttachSystem(system)
vis.SetWindowSize(1280, 720)
vis.SetWindowTitle('Masonry Box Collapse Simulation (Antigravity Explicit Physics)')
vis.Initialize()
vis.AddLogo(chronoirr.GetChronoDataFile('logo_pychrono_alpha.png'))
vis.AddSkyBox()
vis.AddCamera(chrono.ChVector3d(wall_width * 1.5, wall_height, -wall_height))
vis.AddTypicalLights()

step_time = 0.005
wind_duration = {wind_duration}

while vis.Run():
    vis.BeginScene()
    vis.Render()
    vis.EndScene()
    
    # Wind Duration Cut-off Logic (Impulse blast)
    if system.GetChTime() > wind_duration:
        # Turn off wind force on all South wall bricks
        for b in bricks:
            forces = b.GetForceList()
            if len(forces) > 0:
                forces[0].SetMforce(0.0)
                
    system.DoStepDynamics(step_time)
'''
    return script
