# PyChrono Script for Dynamic Masonry Wall Collapse
# Generated by Antigravity Masonry Simulator

import pychrono as chrono
import pychrono.irrlicht as chronoirr
import math

# 1. System Configuration
system = chrono.ChSystemNSC()
system.Set_G_acc(chrono.ChVector3d(0, -9.81, 0))

# 2. Material properties for bricks and mortar interaction
brick_material = chrono.ChContactMaterialNSC()
brick_material.SetFriction(0.6)
brick_material.SetRestitution(0.1)
# Cohesion simulates the mortar bond strength before failure
brick_material.SetCohesion(50000) # Reduced to allow yielding under 135mph+ winds

# 3. Geometric Parameters
brick_x = 0.20 # 20cm length
brick_y = 0.10 # 10cm height
brick_z = 0.2  # Thickness requested

wall_width = 5.0
wall_height = 3.2

cols = int(wall_width / brick_x)
rows = int(wall_height / brick_y)

has_window = True
w_width = 1.0
w_height = 1.2
s_height = 0.9

# Central window limits
w_x_min = (wall_width - w_width) / 2.0
w_x_max = w_x_min + w_width
w_y_min = s_height
w_y_max = s_height + w_height

def is_inside_opening(x, y):
    if not has_window: return False
    # Check if brick center is inside the window box
    return w_x_min < x < w_x_max and w_y_min < y < w_y_max

bricks = []

# 4. Wall Construction Loop (Running Bond Pattern)
for r in range(rows):
    off_x = (r % 2) * (brick_x / 2.0)
    for c in range(cols):
        pos_x = c * brick_x + off_x
        pos_y = r * brick_y + (brick_y / 2.0)
        
        # Omit bricks that fall inside the window
        if not is_inside_opening(pos_x, pos_y):
            brick = chrono.ChBodyEasyBox(brick_x, brick_y, brick_z, 1800, True, True, brick_material)
            brick.SetPos(chrono.ChVector3d(pos_x, pos_y, 0))
            system.Add(brick)
            bricks.append(brick)
            
            # Apply Lateral Wind Load as constant force (simplified equivalent pressure * area)
            wind_press = 3.8 * 1000 # Pa
            face_area = brick_x * brick_y if "Out-of-plane (perpendicular to wall)" == "Out-of-plane (perpendicular to wall)" else brick_y * brick_z
            force_mag = wind_press * face_area
            
            # Use ChForce to apply lateral loads
            myforce = chrono.ChForce()
            brick.AddForce(myforce)
            myforce.SetMode(chrono.ChForce.FORCE)
            if "Out-of-plane (perpendicular to wall)" == "Out-of-plane (perpendicular to wall)":
                myforce.SetVrelpoint(chrono.ChVector3d(0, 0, 0))
                myforce.SetMforce(force_mag)
                myforce.SetDir(chrono.ChVector3d(0, 0, 1)) # Z direction
            else:
                myforce.SetVrelpoint(chrono.ChVector3d(0, 0, 0))
                myforce.SetMforce(force_mag)
                myforce.SetDir(chrono.ChVector3d(1, 0, 0)) # X direction

# 5. Fixed Ground/Support (Engaste)
floor = chrono.ChBodyEasyBox(wall_width * 2, 0.5, wall_width * 2, 1000, True, True, brick_material)
floor.SetPos(chrono.ChVector3d(wall_width / 2.0, -0.25, 0))
floor.SetFixed(True)
system.Add(floor)

# Simulate Fixed Base by severely restricting the lowest course of bricks
# This creates the "engaste" effect required to correlate with Abaqus.
for b in bricks:
    pos = b.GetPos()
    if pos.y < brick_y: # Bottom row
        b.SetFixed(True)

# 6. Optional FRP Reinforcement Loop
apply_frp = False
if apply_frp:
    print("Applying FRP strips (using constraints/FEA) as stabilization...")
    # FEA mesh logic would be implemented here bridging vertical strips mapping.

# 7. Visualization Loop
vis = chronoirr.ChVisualSystemIrrlicht()
vis.AttachSystem(system)
vis.SetWindowSize(1280, 720)
vis.SetWindowTitle('Masonry Wall Collapse Simulation (Antigravity)')
vis.Initialize()
vis.AddLogo(chronoirr.GetChronoDataFile('logo_pychrono_alpha.png'))
vis.AddSkyBox()
vis.AddCamera(chrono.ChVector3d(wall_width / 2.0, wall_height / 2.0, -wall_height * 1.5))
vis.AddTypicalLights()

while vis.Run():
    vis.BeginScene()
    vis.Render()
    vis.EndScene()
    system.DoStepDynamics(0.005)
